###
version : "3"
services:
   nginxwebdemo:
      image: "mkbahk/nginxwebdemo:latest"
      build:
         context: .
         dockerfile: ./Dockerfile
      deploy:
         replicas: 5
         restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 3
            window: 60s
         resources:
           limits:
             cpus: "0.1"
             memory: 50M
      ports:
         - "8380:80"
      networks:
         - nginx-net
networks:
   nginx-net:
###
#docker stack deploy -c docker-stack-compose.yaml nginxwebdemostack
#docker stack ls
#docker service ls
#docker stack rm nginxwebdemostack
