###
version : "3"
services:
   nginxwebdemo:
#      image: "mkbahk/nginxwebdemo:latest"
      build:
         context: .
         dockerfile: ./Dockerfile
      ports:
         - "8380-8389:80"
      networks:
         - nginx-net
networks:
   nginx-net:
###
#docker-compose up -d --build
#docker-compose down --rmi all
#
#docker-compose up -d --build --scale nginxwebdemo=10
#docker-compose up --scale nginxwebdemo=5
#docker-compose down --rmi all
#
###

