###
version : "3"
services:
   nginxwebdemo:
      image: "mkbahk/nginxwebdemo:latest"
      deploy:
         replicas: 5
         restart_policy:
            condition: on-failure
         resources:
           limits:
             cpus: "0.1"
             memory: 50M
      ports:
         - "8380:80"
      networks:
         - nginx-net
networks:
   nginx-net:
###
#docker stack deploy -c docker-stack-compose.yaml nginxstack
#docker stack ls
#docker service ls
#docker stack rm nginxstack
