---
apiVersion: v1
kind: Service
metadata:
  name: nginxwebdemo-svc
spec:
  #clusterIP: x.y.w.z
  selector:
    "app": "nginxwebdemo"
  ports:
  - protocol: TCP
    port: 8380
    targetPort: 80
  type: LoadBalancer
---