---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxwebdemo-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      "app": "nginxwebdemo"
  template:
    metadata:
      name: nginxwebdemo-pod
      labels:
        "app": "nginxwebdemo"
    spec:
      containers:
      - name: nginxwebdemo-container
        image: mkbahk/nginxwebdemo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxwebdemo-svc
spec:
  #clusterIP: x.y.w.z
  selector:
    "app": "nginxwebdemo"
  ports:
  - protocol: TCP
    port: 8380
    targetPort: 80
  type: LoadBalancer
---
#LB공인IP->Server:8380 -> Deployment -> ReplicaSet->POD:80->Container:nginxwebdemo:latest
---